[project]
name = "chat-bot-maestro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymupdf>=1.26.3",
    "requests>=2.32.4",
    "streamlit>=1.47.0",
]
